local alienTexture = MOAIImage.new()
alienTexture:load("resources/graphics/alien.png")
alienDeck = MOAIGfxQuad2D.new()
alienDeck:setTexture(alienTexture)
alienDeck:setRect(-64, -64, 64, 64)
local heroTexture = MOAIImage.new()
heroTexture:load("resources/graphics/hero.png")
heroDeck = MOAIGfxQuad2D.new()
heroDeck:setTexture(heroTexture)
heroDeck:setRect(-64, -64, 64, 64)
local ufoTexture = MOAIImage.new()
ufoTexture:load("resources/graphics/ufo.png")
ufoDeck = MOAIGfxQuad2D.new()
ufoDeck:setTexture(ufoTexture)
return ufoDeck:setRect(-64, -64, 64, 64)
